### ISSUE TITLE
Request: add support for Kega Fusion plugin system

### ISSUE THREAD

**Issue by openfroze** [Yabause/yabause#114]
is it possible to add support for Kega Fusion plugin system? filters like xBR would be available by this

**Comment by wingedonezero** [comment]
+1

**Comment by cyberwarriorx** [comment]
Filters will be probably added at some point, however plugins will never happen. Yabause has always had a policy of never depending on closed software. 
Since there's a few duplicate issues, I refer to: https://github.com/Yabause/yabause/issues/16 https://github.com/Yabause/yabause/issues/99
