### ISSUE TITLE
Aspect ratio is not kept

### ISSUE THREAD

**Issue by v-fox** [Yabause/yabause#13]
Please, make yabause keep aspect ratio of the picture, without it and any kind of improved scaling it looks horrendous. In fullscreen it's all stretched up and in window mode one has to correct the size pixel by pixel manually which is quite insane.

**Comment by Guillaumito** [comment]
Fixed in a5d443e987fc0a127915cadae6b12e71676cf16d
(but the fullscreen should already have been correct...)
