### ISSUE TITLE
Guardian Heroes stuck on Stage 2

### ISSUE THREAD

**Issue by 3xcl4m4t10n** [Yabause/yabause#136]
Hello team:

After defeating the cyclop the game stuck suddenly. I try it on several versions (0.9 & 0.9.14, also on Yabause-rr -I know it's an unofficial release-). Also I try different regions (NTSC-U & J) and different rips from different authors & different formats (cue, mdf, iso...) but always happen the same. I found a video where you can see the exact moment where it happen:

https://youtu.be/eJE2qXtH7lE?t=16m

As you can heard there's a music change but apparently there's no any other big change on the game. In this video you can see the freeze section and when and how it happen:

https://youtu.be/WbifmxETocE?t=10m5s

Is this a known issue or something? Thank you so much!

**Comment by d356** [comment]
This should be working since 41d71e38e47d39d5fe12215d651a97a65391017a

**Comment by Mori-S** [comment]
Works fine with the Japanese release. Shot from stage03:
![stage03](https://cloud.githubusercontent.com/assets/15892211/14061203/c399c0b6-f337-11e5-8460-f0acd09b6ac1.png)

**Comment by 3xcl4m4t10n** [comment]
@d356, thank you for the information :D.

@Mori-S, this is the leaked version of some days or the last official version of the emulator? I tried with all the versions (JP, US & EU) but maybe was a bad rip or something like that.

**Comment by Mori-S** [comment]
@3xcl4m4t10n Nah I built it using visual studio. I don't like releasing builds so you'll have to wait for the next release or get it from a site like emucr, but I wouldn't recommend it because I think some of the sites they use to host the files on have malware

**Comment by d356** [comment]
Closing since the bug has been fixed. We also now have development versions available to download at https://yabause.org/download/

**Comment by zellalove** [comment]
ok, so for someone like me who doesnt know "code" what does any of this mean i too get stuck at stage 2.  can you just make a link to a zip file for the new and working guardian heroes "ROMenurals" or for a better emulator.   im 32 bit windows.  preferable an executable emulator.  i dont have install privileges at my sometimes super boring job.
