### ISSUE TITLE
Picture looks horrendous without filtering

### ISSUE THREAD

**Issue by v-fox** [Yabause/yabause#14]
Unfortunately, non-filtered upscaled picture in yabause looks super terrible, worse than GBA games. Filters and any other kind of upscaling compensation is extremely needed. For now, however, there are ways to force-enable some filtering externally. Like running
`env pp_jimenezmlaa_color=8 yabause` under Mesa/Gallium
and improving this
![20150711-185008](https://cloud.githubusercontent.com/assets/362763/8634032/53723fbe-2800-11e5-9aa5-469180f12cb2.png)
to this
![20150711-185201](https://cloud.githubusercontent.com/assets/362763/8634033/5afb6a26-2800-11e5-8f0a-92ee2709f263.png)

**Comment by cyberwarriorx** [comment]
Added: https://github.com/Yabause/yabause/commit/9e42bee055d79c09f113cccbf65ba5c7d6af1c8e
