### ISSUE TITLE
Tempest 2000 boots but no respond to controls... Other games work.

### ISSUE THREAD

**Issue by frenchfriess** [Yabause/yabause#146]
Using the latest updated Retroarch build.

Emulator works fine.

bomberman works
astal works

**Comment by frenchfriess** [comment]
What the hell? thing cut me short... anyway I have the emulator set up correctly and other games work.

Something's wrong with tempest 2000 and the controls... It does not respond.

**Comment by vgturtle127** [comment]
@frenchfriess Have you tried with non-RetroArch Yabause?

**Comment by CandyFace** [comment]
Can't reproduce this, works fine on vanilla Yabause from git. It may have been fixed or has never really been a problem on vanilla Yabause.

**Comment by vgturtle127** [comment]
@CandyFace Yeah, I can't reproduce this.

@frenchfriess Maybe try again with a fresh install?

**Comment by frenchfriess** [comment]
Well who's in charge of the retroarch yabause? thats the one I'm trying to use. I like the retroarch all in 1 simplicity and most of all the shader options.

**Comment by CandyFace** [comment]
None in this repo as far as I know, the Retroarch yabause is a fork which is modified. You should post the issue there instead. https://github.com/libretro/RetroArch/issues

**Comment by vgturtle127** [comment]
@frenchfriess I think TwinAphex knows about most of the changes, so you could try talking to him about it.

If you have the same problem in regular Yabause, then we can discuss debugging the issue in further detail.

This would be a RetroArch issue as far as I can tell, though, not a Yabause issue. Please post there and close this issue, if you don't have issue with vanilla Yabause.

**Comment by frenchfriess** [comment]
roger
