### ISSUE TITLE
[Athlete Kings] GFX Problem

### ISSUE THREAD

**Issue by BenjaminSiskoo** [Yabause/yabause#156]
Yabause 02.21.2016 (Software)

horizontal lines in game (characters, menu, etc...) The game is slowest.
![athletekings](https://cloud.githubusercontent.com/assets/12481242/13202249/4bb196b8-d894-11e5-91a7-78d33eac67d8.png)

**Comment by d356** [comment]
This game runs in an interlaced video mode and the lines are interlacing artifacts that also appear on a real Saturn. I can't find any good Saturn video but the left image in this hardware capture is the same sort of video mode: http://i.imgur.com/TuUqIi4.png

**Comment by BenjaminSiskoo** [comment]
Here a picture from the last official yabause 0.9.14

Dead or Alive got the same artefacts

![athlete kings](https://cloud.githubusercontent.com/assets/12481242/13317855/a1503784-dbb7-11e5-99af-369444514233.png)

**Comment by d356** [comment]
The reason that Yabause 9.14 looks different is because it doesn't support high resolution or interlaced modes. Dead or Alive has the same artifacts because it also uses interlaced video.

**Comment by BenjaminSiskoo** [comment]
Ok.Do you think it's possible to fix it ?

**Comment by d356** [comment]
An enhancement option could be added that draws all lines every frame but it would run at 1/2 of the current speed.

**Comment by BenjaminSiskoo** [comment]
Ok I see. Btw, good to have some answers :)

**Comment by Mori-S** [comment]
Does it draw the software rendering using opengl? Would something like a deinterlacing shader work rather than losing half the frames by drawing both? Sorry I don't really know much about this stuff :/

**Comment by d356** [comment]
Yes, the Qt port uses OpenGL for presentation and a shader could be used to get a similar effect with less of a performance hit.

**Comment by BenjaminSiskoo** [comment]
Fixed
