### ISSUE TITLE
[Memory Editor] VDP2 registers

### ISSUE THREAD

**Issue by shazz** [Yabause/yabause#167]
If I'm not wrong the states of the VDP2 registers are not updated (read and write) at 0x5F80000, only zeroes.
05F80000-05FBFFFF : VDP2 registers (512 bytes, mirrored every 512 bytes)

![editor](https://cloud.githubusercontent.com/assets/604708/13205225/515056aa-d8b1-11e5-9260-6d74f7891dcd.png)

**Comment by cyberwarriorx** [comment]
Memory Editor is based on SCU addresses and read/write access similar to a real Saturn. That means most VDP2 registers are write-only.

**Comment by shazz** [comment]
Some are readonly but definitively not all (BGON, CYC*,
CHCTL*, PNCN*... are RO). And here I just see zeroes. 
For example, TVSTAT is read only.
