### ISSUE TITLE
Super Adventure Rockman Issues

### ISSUE THREAD

**Issue by Camtronic16** [Yabause/yabause#169]
When me and my sister played on Super Adventure Rockman, we discovered some issues.
(Note: The ISOs in particular are from emuparadise)

Disk 1 freezes at the end of the Capcom intro logo, unless skipped before it fully plays. Afterwards, it works fine, albeit with some minor FMV playback related glitches.

Disk 2 freezes with black screen and occasionally causes yabause to stop responding.

Disk 3 works normally, with the same FMV issues as disk 1.

The FMV issues are that the movies sometimes speed-up and/or sometimes loses sync with the audio for a short moment. However, we are not sure if that is an ISO problem or not. 

This was done on Windows 10 using Yabause version 0.9.14.

**Comment by Mori-S** [comment]
Not only is the emuparadise version dumped incorrectly, but it's the recalled T-1225G release. This is why you should buy the games and dump them yourself or find a better source. I'm sure the developers don't like people using pirated copies either

http://segaretro.org/Super_Adventure_Rockman

**Comment by Camtronic16** [comment]
Oh, okay. Thank you for clearing that up. :)

**Comment by Mori-S** [comment]
No problem. Hope you manage to find a working copy. Not sure if editing the cue sheet will fix it or not seeing as it was recalled

**Comment by cyberwarriorx** [comment]
So was this game actually working then?

**Comment by Camtronic16** [comment]
@cyberwarriorx Yes. The game was working, despite the problem mentioned by @Mori-S.

**Comment by cyberwarriorx** [comment]
Ok. I'll close it then.

**Comment by Mori-S** [comment]
The cue sheet was borked when I looked at it. I just figured if it was recalled there would have been a problem with the game. I checked the dump with a hex editor to make sure the serial matched up
