### ISSUE TITLE
[Akumajou Dracula X] Missing portraits...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [Yabause/yabause#173]
Yabause 02.29.2016 (Software)

In game, after pushing start, in the menu, portraits are missing.

![akumojo dracula](https://cloud.githubusercontent.com/assets/12481242/13391282/dd4b48ae-ded3-11e5-9b59-39d77a196751.png)

It looks like it's the same problem than OpenGL mode

https://github.com/devmiyax/yabause/issues/171

**Comment by jvhellraiser** [comment]
i have another screenshot, hope it helps
![capture](https://cloud.githubusercontent.com/assets/16488761/13590531/eaadc484-e4b6-11e5-8097-c88cf86dc973.PNG)

**Comment by BenjaminSiskoo** [comment]
Nope, ca n'a rien changé :)

**Comment by Guillaumito** [comment]
That's really weird... I cannot reproduce this bug...

That's what I have with my build of the current git repository:
![dx-portrait](https://cloud.githubusercontent.com/assets/420934/13684992/a4243f7a-e70e-11e5-9f28-374aaa751faf.png)

**Comment by BenjaminSiskoo** [comment]
Fixed :)
