### ISSUE TITLE
Can't initialize Yabause

### ISSUE THREAD

**Issue by Marc34** [Yabause/yabause#179]
Hi,

For all games I try with OpenGL, I obtain this message : 

Can't initialize Yabause

Log :

Fail to YglProgramInit

Cannot initialize Vidéo

(Yabause Qt compiled on Ubuntu 16.04).

**Comment by Guillaumito** [comment]
Sounds like a problem with "modern" OpenGL. Did you try compiling it in "full software mode" : by setting YAB_WANT_OPENGL to OFF?

**Comment by Marc34** [comment]
Yes, it works with software mode.

**Comment by Guillaumito** [comment]
Ok, so... your options are to keep using the software mode (like me...) or change your graphic card/drivers to something that supports modern OpenGL.

**Comment by Marc34** [comment]
ok, too bad.

**Comment by Marc34** [comment]
Le pilote propriétaire fournit OpenGL4, mais est parfois de 75% (!!) moins performant que le pilote libre. Pilote libre qui ne prend pas en charge OpenGL 4...

**Comment by OKB-99** [comment]
Have you solved this actually???
If not yet, let me know the output of 
`glxinfo | grep OpenGL`
and
`lspci -v | grep -A 10 VGA`

**Comment by gittyno1** [comment]
i just get "Can't initialize Yabause"

**Comment by OKB-99** [comment]
In my case, the cause was that _shading language version_ of OpenGL was too old.
You can check it by `$ glxinfo | grep OpenGL`. 

If you have the same problem, you can fix it according to this post. 
https://github.com/Yabause/yabause/issues/349#issuecomment-332987246

You need to recompile after the env setting.

**Comment by TsukiZero** [comment]
Getting this issue for no reasion whatsoever
