### ISSUE TITLE
Shining Force 3 (All Scenarios) - Purple around text on main screen

### ISSUE THREAD

**Issue by rdanbrook** [Yabause/yabause#194]
![sf3](https://cloud.githubusercontent.com/assets/1869094/13893619/7b16944c-ed36-11e5-83dc-fe76626d44f7.jpg)

Probably something similar to #175 
Specifically where it says "PRESS START BUTTON"

**Comment by cyberwarriorx** [comment]
I'm pretty certain it's supposed to look like that. Here's a compare between a real saturn and latest Yabause for first scenario:

![sf3-realsaturn](https://cloud.githubusercontent.com/assets/3471977/14118588/27aef8b4-f5b8-11e5-97fa-8a83696313b8.jpg)
![sf3-yabause](https://cloud.githubusercontent.com/assets/3471977/14118591/2af7008e-f5b8-11e5-8606-f9996945c240.png)
