### ISSUE TITLE
[Fantastic Pinball Kyutenkai (J)] Regression...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [Yabause/yabause#237]
The game "works" with Yabause Git 04.21.2013. And there is a black screen (built in and real bios) with Yabause Git 04.23.2016...

**Comment by d356** [comment]
I tested this and I'm not seeing a regression. It goes in-game but is unplayable due to a palette issue as it was before.

**Comment by BenjaminSiskoo** [comment]
Tested with the last sources, same problem. Are you trying the 32 Bits release ?

**Comment by d356** [comment]
My 32-bit build doesn't seem to have any regressions either.

**Comment by BenjaminSiskoo** [comment]
Fixed (delete ini file)
