### ISSUE TITLE
[UI improvement] Bios button...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [Yabause/yabause#266]
Is it possible to add a button in the Qt UI to enable/disable bios ?

Here an idea :

Enable --> built in bios.
Disable --> real bios.

**Comment by cyberwarriorx** [comment]
I already did?

**Comment by BenjaminSiskoo** [comment]
Yup in the tab. Not in the GUI ^^

![yabause_button](https://cloud.githubusercontent.com/assets/12481242/15127280/3b39c51e-1636-11e6-8af3-5ecc763e77ad.JPG)

**Comment by cyberwarriorx** [comment]
Is it really that necessary to have in the toolbar though?

**Comment by BenjaminSiskoo** [comment]
For most people, I guess not. To me, I could save some time :)
