### ISSUE TITLE
Albert Odyssey regression

### ISSUE THREAD

**Issue by BenjaminSiskoo** [Yabause/yabause#27]
Left picture : Yabause git 07.31.2015
Right picture : Yabause git 03.08.2015

![albert odyssey](https://cloud.githubusercontent.com/assets/12481242/9035223/4ad8f6e4-39d6-11e5-8573-daaeac2cfd29.PNG)

**Comment by cyberwarriorx** [comment]
We're happy to see you alive and working your magic! :) Everyone on #yabause was wondering what happened to the legendary Crazy Tester.

**Comment by Guillaumito** [comment]
Siskoooooooo!!! :D
