### ISSUE TITLE
iOS Version Of Yabause

### ISSUE THREAD

**Issue by mk8itra1n** [Yabause/yabause#273]
Just wondering if you guys are considering working on a version of Yabause for Apple iOS as I see you have already released a Yabause app for android. You guys could totally put it on the Cydia Store for jailbroken devices or have no jailbroken devices sideload it through the safari web browser or Xcode on the Mac. I think the specs are decent enough for it to able to run on these devices. Looking forward to hearing from you guys👍

**Comment by d356** [comment]
Devmiyax was working on an iOS port earlier this year, you may want to ask him about it: https://www.youtube.com/watch?v=duf1GJbLpos

**Comment by mk8itra1n** [comment]
@d356 Holy Crap I've never seen this video before. The progress he's made on it looks amazing tho. Almost 60fps all the time is pretty impressive on the iPhone 6 Plus. Does he have a github page as well or did he just upload that one video to YouTube. It would help if he had a github or Twitter at least

**Comment by d356** [comment]
His github and twitter are https://github.com/devmiyax/yabause and https://twitter.com/miyaxdev

**Comment by mk8itra1n** [comment]
Thx for the help!
