### ISSUE TITLE
[Language] Update french file...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [Yabause/yabause#279]
http://forums.yabause.org/index.php?topic=9386.0

**Comment by d356** [comment]
We're testing out a new translation system, would you mind taking a look? https://www.transifex.com/yabause/public/

There's currently 16 new strings that need to be translated to French.

**Comment by BenjaminSiskoo** [comment]
Ok I'm waiting the access :)

**Comment by BenjaminSiskoo** [comment]
Done, They are lot missings strings in transiflex. On yabause_fr.yts, you could get more strings to add :)

**Comment by d356** [comment]
Thanks, I added some more missing strings. If there are more missing could you post them here?

**Comment by BenjaminSiskoo** [comment]
Here more strings : 

%1 Images (*.%2)
3D Control Pad Configuration
68000 core
All Files
Can't plug in the new controller, cancelling.
CD Images (*.iso *.cue *.bin *.mds *.ccd)
Choose a binary or program file
Choose a bios file
Choose a folder to store save states
Choose a sh1 rom
Compatibility List
Debug SCSP
Filter mode
Gun|Pistolet
Gun Configuration|Configuration du Pistolet
Remove Peripheral
Save As Bitmap
Shortcut
Sound...
Stick left button: same as A
Stick right button: same as B
Stick trigger: same as C
Stop
VDP2Viewer Viewer
Warning...|Avertissement...
Wheel Configuration

Typo problem !!!

Unknow --> Unknown 

I know there are more strings. I'm going to wait your next commit, to complete the translation...

**Comment by d356** [comment]
Thanks, I've added these strings.

**Comment by BenjaminSiskoo** [comment]
Translated. Is it possible to have the file to test and check some remaining strings ?

**Comment by d356** [comment]
I updated the translations in d9bd0bb0a94b35bff62338bc614e52b1ac90a9b7

**Comment by BenjaminSiskoo** [comment]
I cannot use a translation file. 

strings looks like this in the "old" file : file|fichier
with the new one : "file","fichier"

Any changes with the translation compilation ?

**Comment by d356** [comment]
The file format was changed to http://docs.transifex.com/formats/magento-csv/
Basically strings need to be inside "" and separated by a comma.

**Comment by BenjaminSiskoo** [comment]
ok. Is it possible to give me the way to use the new format !!!

**Comment by d356** [comment]
You should be able to download yabause_en.csv ( French ) from transifex. You can just add any missing strings to that file to test with, but it needs to be renamed to yabause_fr.yts and put in the trans directory. Once you've decided what strings you want added you can just post them here and I'll add them to the main file.

**Comment by BenjaminSiskoo** [comment]
I'll check that next week.

**Comment by BenjaminSiskoo** [comment]
Here more strings : 

Assembly code
Choose a location for your bitmap
Choose a location for your binary file
Choose a location for your wav file
Enter new assembly code:
Inline Assembly
Binary Files (*.bin)
COFF Program Files (*.cof *.coff)
ELF Program Files (*.elf)
All Files (*)
Loop Track Stop
SH1 Registers
SH1 Interpreter
WAV Files (*.wav)
Left stick:
Right stick:
Trigger:
Left button:
Right button:

The way you talk about is not working. Do I need to compile mini18n to use the csv translation ? Or I should to create a trans folder and put the csv file in ?

**Comment by d356** [comment]
Thanks for the strings. mini18n is still required, the Travis CI builds don't work because they don't have mini18n included.

**Comment by BenjaminSiskoo** [comment]
ok. I guess I could find some hidden strings, but for now, it's ok :)

**Comment by BenjaminSiskoo** [comment]
From post-0.9.15 branches.

New string : Enable SCSP DSP Dynamic Recompiler.

2 questions about this build. What does exactly Codegen ? What is the new option DSP Dynamic Recompiler ?

**Comment by d356** [comment]
Thanks, I've added the string. CodeGen is a library from the Play! PS2 emulator that generates code at run-time. The new option uses this library to try and make the new SCSP faster.

**Comment by BenjaminSiskoo** [comment]
Ok thanks :)
