### ISSUE TITLE
[Deathmask] Crash at the start...

### ISSUE THREAD

**Issue by BenjaminSiskoo** [Yabause/yabause#317]
Yabause 0.9.15 05.08.2016 (Software) (64 bits)

Yabause crashes at the start of the game : 

![deathmask](https://cloud.githubusercontent.com/assets/12481242/17456186/1f0b7af2-5bcf-11e6-86e5-4002ecc8a10c.JPG)

**Comment by d356** [comment]
Could you try a Debug build and post the stack trace (Pile des appels)?

**Comment by BenjaminSiskoo** [comment]
With Yabause 0.9.15 (public release), the  game is ok (except glitches ingame).
