### ISSUE TITLE
Behaviour problem with cheat search

### ISSUE THREAD

**Issue by BenjaminSiskoo** [Yabause/yabause#34]
I can make Yabause crashes like this : 
- launch yabause
- Tools --> Cheat Search
- Search value field : fill it with a number
- Click on Start 
- Click on Search.

Yabause crashes

**Comment by cyberwarriorx** [comment]
Fixed: https://github.com/Yabause/yabause/commit/653c264f1900a5718b86a183a321d653dc4019cb
