### ISSUE TITLE
Mouse binding problem

### ISSUE THREAD

**Issue by BenjaminSiskoo** [Yabause/yabause#35]
I can't bind the mouse buttons. 
- launch Yabause.
- File --> Settings --> Input Tab.
- Select the mouse.
- Press the B button to set it.
- Press the left button of your real mouse and it does'nt works.

**Comment by cyberwarriorx** [comment]
Fixed: https://github.com/Yabause/yabause/commit/3eac228f33c0e617f881a91a6a9eae936018f186
