### ISSUE TITLE
"relocation R_X86_64_32S against undefined symbol"

### ISSUE THREAD

**Issue by Marc34** [Yabause/yabause#358]
I use Ubuntu 16 10 and I can't compile Yabause :

[100%] Linking CXX executable yabause-qt
/usr/bin/ld: ../libyabause.a(linkage_x64.s.o): relocation R_X86_64_32S against undefined symbol `master_ip' can not be used when making a shared object; recompilé avec -fPIC
/usr/bin/ld : échec de l'édition de liens finale : Section non-représentable pour la sortie
collect2: error: ld returned 1 exit status
src/qt/CMakeFiles/yabause-qt.dir/build.make:2577 : la recette pour la cible « src/qt/yabause-qt » a échouée
make[2]: *** [src/qt/yabause-qt] Erreur 1
CMakeFiles/Makefile2:286 : la recette pour la cible « src/qt/CMakeFiles/yabause-qt.dir/all » a échouée
make[1]: *** [src/qt/CMakeFiles/yabause-qt.dir/all] Erreur 2
Makefile:149 : la recette pour la cible « all » a échouée
make: *** [all] Erreur 2

Any idea ?

**Comment by Guillaumito** [comment]
Yeah, that's a know bug, see: https://github.com/Yabause/yabause/issues/270

For now, compile without the dynarec, using something like:

cmake -DSH2_DYNAREC=OFF ...

**Comment by Marc34** [comment]
ok, thank for the answer.
