### ISSUE TITLE
Behaviour problem part 2

### ISSUE THREAD

**Issue by BenjaminSiskoo** [Yabause/yabause#36]
* launch yabause --> debug --> scudsp --> code breakpoints --> add a value --> add and Yabause crash 
* launch yabause --> debug --> scudsp --> memory breakpoints --> add a value --> add and Yabause crash 
* launch yabause --> debug --> m68k--> code breakpoints --> add a value --> add and Yabause crash 
* launch yabause --> debug --> VDP2 --> Viewer and Yabause crash

**Comment by cyberwarriorx** [comment]
There's no SCU DSP memory breakpoints. Did you possibly mean m68k?

**Comment by BenjaminSiskoo** [comment]
copy past is the evil :)

• launch yabause --> debug --> master SH2 --> code breakpoints --> add a value --> add and Yabause crash
• launch yabause --> debug --> master SH2 --> memory breakpoints --> add a value --> add and Yabause crash
• launch yabause --> debug --> slave SH2 --> code breakpoints --> add a value --> add and Yabause crash
• launch yabause --> debug --> slave SH2 --> memory breakpoints --> add a value --> add and Yabause crash

**Comment by cyberwarriorx** [comment]
ok :)

**Comment by cyberwarriorx** [comment]
Fixed: https://github.com/cyberwarriorx/yabause/commit/865e37435b414ba6a1a381b56f10ae120e798595
