### ISSUE TITLE
Serious compiler warnings

### ISSUE THREAD

**Issue by nevat** [Yabause/yabause#37]
Hi,

Building a RPM package for openSUSE (get the code from git version), I get this errors in two files.

64bit-portability-issue yabause/src/vidogl.c:4001
64bit-portability-issue yabause/src/ygles.c:2398, 2413

Thanks for your work !

**Comment by cyberwarriorx** [comment]
Fixed: https://github.com/Yabause/yabause/commit/8ac262933b66d834d9504e78b45029b58bbd793b
