### ISSUE TITLE
Question for yabause

### ISSUE THREAD

**Issue by azoreseuropa** [Yabause/yabause#400]
I love SSF but I am keeping my eyes on yabause as well. Are you still working on this project, right ? Curiosity. :)

**Comment by anewuser** [comment]
Please don't open Github issues to ask that. Just check the "Graphs" tab. https://github.com/Yabause/yabause/graphs/contributors .

If you believe that developers should be more active, become a patreon: https://yabause.org/ .

**Comment by cyberwarriorx** [comment]
You can also contact us directly.
