### ISSUE TITLE
D-Pad input not recognized in game

### ISSUE THREAD

**Issue by acidmanifesto** [Yabause/yabause#403]
Windows 10 home 64bit creator's edition. I gone thru all 4 profiles under input and reput in all the buttons configurations. And the buttons are registering during configurations. However when i play the games, the D-Pad is not working at all in game. I used multiple controllers, xbox 360, play sega, xbox one and ps4 controllers and it is all the same. The D-Pad is not working at all in Game.

**Comment by BenjaminSiskoo** [comment]
Try this : 

1) Download the latest UoYabause.
2) Unzip it.
3) Get yabause.ini file from C:\Users\username\AppData\Local\yabause
4) Put it in the root of your latest Uoyabause than you unzipped.
5) Open yabause.ini, erase all, save.
6) Setting up and it should work.

**Comment by acidmanifesto** [comment]
That worked. Thank you

**Comment by BenjaminSiskoo** [comment]
Nice :)

**Comment by NightStarX** [comment]
This does NOT work for me... even doing that, does not work. No matter how I set up Yabause, the D-pad will say it's set up in input but will NOT function in any game. I can't go up, right, left, or down in anything, and the above does not help the situation.
