### ISSUE TITLE
qtmultimedia4.dl is still not found.

### ISSUE THREAD

**Issue by twarnercool2** [Yabause/yabause#49]
Not sure if its the Emucr version but I still get soothing saying qtmultimedia4.dl is not found. I have windows 10 64 bit.

**Comment by cyberwarriorx** [comment]
This is our policy relating to builds coming from emucr, etc. http://forums.yabause.org/index.php?topic=439.0

I double checked it and it works fine here. Perhaps whoever built it didn't update it correctly to the newest version.

**Comment by twarnercool2** [comment]
What grapics card do you have?
