### ISSUE TITLE
Filtering Bilinear menu

### ISSUE THREAD

**Issue by BenjaminSiskoo** [Yabause/yabause#54]
There is a display problem with the bilinear filtering menu. Check the picture. 

![bf](https://cloud.githubusercontent.com/assets/12481242/9427594/77a92ab2-4986-11e5-91d5-dad663d356c1.PNG)

**Comment by cyberwarriorx** [comment]
Fixed: https://github.com/Yabause/yabause/commit/0f8095b5a628d234e2979ddd816560f2d3d53d53

**Comment by Guillaumito** [comment]
No, this option has not been included in the gtk interface.

**Comment by mckaygerhard** [comment]
ah oh, well, "its or not its" now we are shakespeare lovers?

please can u tell the commit (due the issue # 67 while still are)  to backport to my older version , i need to made compile in a embebed device and some thing for lasted git are not possible due  # "67"
