### ISSUE TITLE
Mouse focus.

### ISSUE THREAD

**Issue by BenjaminSiskoo** [Yabause/yabause#55]
The problem exists in fullscreen / windowed screen.

When you move the mouse in Yabause, the mouse move on the desktop too.

**Comment by cyberwarriorx** [comment]
Need more info. But if it's what I think it is, the regular mouse cursor and in game mouse cursor are always moving when you move the mouse.

**Comment by BenjaminSiskoo** [comment]
I forgot to add a video. 

https://youtu.be/5vB6o58_9DM

**Comment by BenjaminSiskoo** [comment]
Perfect. I like the way you can use the ESC button. Thanks :)
