### ISSUE TITLE
"V.R racing" and "Tempest 2000" does nothing when start is press

### ISSUE THREAD

**Issue by twarnercool2** [Yabause/yabause#60]
The games go in-game fine, but the controls don't work.

**Comment by d356** [comment]
Controls in both games should be working since e811a3544b3d819b9aaa31d9169ab46462acf7b2

**Comment by BenjaminSiskoo** [comment]
Tempest 2000 works, i guess the other game works too.

**Comment by d356** [comment]
Closing since both games have been confirmed to have working controls.
