### ISSUE TITLE
Play nice with libretro save state mechanism

### ISSUE THREAD

**Issue by Kekun** [Yabause/yabause#64]
Libretro requires the state to be saved to / loaded from a buffer, but `YabSaveState` and `YabLoadState` take a file name.

Making it possible to save / load from `FILE*` would make the transition easy as one can use `fmemopen` or `open_memstream` to turn a buffer into a `FILE*`.

Also, libretro needs to know the size of the memory buffer it must allocate, so adding some way to know it would be needed.

**Comment by Guillaumito** [comment]
I added some new functions to handle saving/loading save states from memory in 7b4e57b46ae8abdfd182769e8765c96941b06cb4
I even tried to write some code to show how it could be used in libretro: https://gist.github.com/Guillaumito/b8ba2bab28bd20865207
