### ISSUE TITLE
INSTALL files still refers to autotools systems and now its cmake

### ISSUE THREAD

**Issue by mckaygerhard** [Yabause/yabause#66]
there's a INSTALL file in sources documents and referes all to older autotools system configuration

and now the yabause uses Cmakefiles for it!

please update the info. PLEASE update with right info for compiling in linux, mac or androit, due i can see that for compiling for linux-like systems (linux, androit, mac) there's no such information about options compilation and tips, if that its so hard for you tell me and i can made a pull request for that.

**Comment by carlospea** [comment]
I read the file INSTALL and says that run "configure" which does not exist

The files README.XX except the README.WIN all say they need but in a very vague way, while the only thing that brings a detailed information on the README.WIN

it suppost that opensource files must apport sometingh to related OS but seems all the opensource project only apport more to the redmon solutions..

**Comment by mckaygerhard** [comment]
oh men wiki are more outdated too! http://wiki.yabause.org/index.php5?title=Compiling_Yabause/linux/linux/qt, no other instruction for others systems and the guindows version are more detailed except for the tortoisesvn are more in sync

well tomorrow i'll registered to the wiki and try to contribute.. **i'm very impressi with the yabause wiki so i'll suggest made a symlink of the github wiki to the yabause domain wiki...**

**Comment by Guillaumito** [comment]
Fixed: b45ccc7f979a59ad59f7a4118f576b4a8fd320df

**Comment by mckaygerhard** [comment]
i'll made a few changes to README and added a minimal USAGE file, can u see and made a review in the pull request?
