### ISSUE TITLE
bug: how can i predefine PAD's in source, gtk crash when try it!

### ISSUE THREAD

**Issue by mckaygerhard** [Yabause/yabause#69]
i research at the sources and in the files linux joy.c or sdljoy.c there's no way to redefine the keyboard buttons.. only joystick related
can any explain me how may pre define pre-configured buttons from the sources?

**Comment by mckaygerhard** [comment]
NOTE: the gtk interface crash when i try to configure buttons: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=703771

**Comment by Guillaumito** [comment]
To use the keyboard, choose "GTK Input Interface".
As for the crash, can you provide a gdb backtrace?
The debian issue is from 2013 and may not be related...

**Comment by mckaygerhard** [comment]
i currently compiling the lasted git (with some hacks, but cannot linking) to test.. and the lasted release and then i feedback to you if still crash

the version that crash to me too was 0.9.10 and 0.9.13 i not tested 0.9.14 yet

**Comment by mckaygerhard** [comment]
Problems still persist in gtk interface lasted git, configuratin under qt does not work due yabause stores per interface config files, so the configuration under qt does not work for gtk

in the .config/yabause/yabause.ini i see only the values for all preferences except for inputs

i see the gtk code but just in that time a flying sucer past thorug my windows and stoled all my knowledg of gtk programing ...
