### ISSUE TITLE
MAME/MESS GPL

### ISSUE THREAD

**Issue by Hydro5** [Yabause/yabause#7]
I think MAME/MESS is going "open source" (I think that this means GPL). Does this mean that code from MESS can now be used in Yabause?

**Comment by cyberwarriorx** [comment]
Assuming it actually goes GPL or a license that is GPL compatible it should be possible.

**Comment by Oggom** [comment]
Apparently it's LGPL-2.1+:

https://github.com/mamedev/mame/blob/master/src/mess/drivers/saturn.c

**Comment by Hydro5** [comment]
Is LPGL 2.1+ compatible with GPL?

**Comment by cyberwarriorx** [comment]
LGPL you mean? It should be.
