### ISSUE TITLE
bug segfault yabause when select opengl video

### ISSUE THREAD

**Issue by mckaygerhard** [Yabause/yabause#73]
program was compiled with qt 4.6.3, mesa 7.2, gcc 4.3.4, gtk 2.20, cmake 2.8.7
running then on xorg 7.10, mesa 7.7, gcc (libstdc++6) 4.4, gtk 2.20, qt 4.7.3

when compiled a "-g" was passed to generated symbols but a very few i cannot foud

running qt interface
1) go to preferences
2) select video
3) select opengl
4) push Acept button
then crash

```
[Thread debugging using libthread_db enabled]

Program received signal SIGSEGV, Segmentation fault.
0x00000000 in ?? ()
(gdb)
```

with gtk too, butr at lease i can save settings due gtk first write to file without too close opengl integration like qt interface

```
Starting program: /usr/bin/yabause-gtk 
[Thread debugging using libthread_db enabled]

Program received signal SIGSEGV, Segmentation fault.
0x00000000 in ?? ()
(gdb) 
```

**Comment by mckaygerhard** [comment]
the emulator was provide of a bios too and segfaulkt too..  software rasterizer gets black screen no sturn screen boot

**Comment by Guillaumito** [comment]
It may be that you don't have support for modern OpenGL. Try compiling Yabause in full software mode with the CMake option -DYAB_WANT_OPENGL=OFF

**Comment by mckaygerhard** [comment]
i right now downloading a bomberman game to test software rasterizer... and then report feedback.. i gess that a support for older opengl will not be due i see the hard work to migrate to modern opengl...

**Comment by mckaygerhard** [comment]
umm i run now bomberman in a bin+cue file, using the iso cd plguin, but only a black screen umm in the code i can see that software render now uses some opengl functions.. its that true?

what opengl extension and what its necesary for runnign each render?

**Comment by rdanbrook** [comment]
The software renderer always used some OpenGL functions. These should really be moved out of vidsoft.c and into the platform specific ports at some point, but baby steps are necessary to avoid serious breakage and unintended consequences.

**Comment by mckaygerhard** [comment]
umm so should i close this bug and use a older version for older setups?
there's some way to provide a compatibility for rare setups, in my maebo i dont have modern opengl and in my very older androit i dont have' so as on my linux DSL

**Comment by mckaygerhard** [comment]
its strange, compiling and older version before 0.9.14 got this error now with yabause 0.9.13 or 0.9.12, using gcc 4.3.2, mesa 7.1, qt 4.6, gtk 2.20, sdl 1.2.14, cmake 2.8.0, any help?:

```
In file included from /media/DATASUPER/MASSENKOH-new/gamesemus/yabause/yabauseet/yabause-0.9.12/src/memory.c:51:
/media/DATASUPER/MASSENKOH-new/gamesemus/yabause/yabauseet/yabause-0.9.12/src/ygl.h:232: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘glIsRenderbuffer’
/media/DATASUPER/MASSENKOH-new/gamesemus/yabause/yabauseet/yabause-0.9.12/src/ygl.h:233: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘glBindRenderbuffer’
/media/DATASUPER/MASSENKOH-new/gamesemus/yabause/yabauseet/yabause-0.9.12/src/ygl.h:234: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘glDeleteRenderbuffers’
/media/DATASUPER/MASSENKOH-new/gamesemus/yabause/yabauseet/yabause-0.9.12/src/ygl.h:235: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘glGenRenderbuffers’
/media/DATASUPER/MASSENKOH-new/gamesemus/yabause/yabauseet/yabause-0.9.12/src/ygl.h:236: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘glRenderbufferStorage’
/media/DATASUPER/MASSENKOH-new/gamesemus/yabause/yabauseet/yabause-0.9.12/src/ygl.h:237: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘glGetRenderbufferParameteriv’
/media/DATASUPER/MASSENKOH-new/gamesemus/yabause/yabauseet/yabause-0.9.12/src/ygl.h:238: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘glIsFramebuffer’
/media/DATASUPER/MASSENKOH-new/gamesemus/yabause/yabauseet/yabause-0.9.12/src/ygl.h:239: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘glBindFramebuffer’
/media/DATASUPER/MASSENKOH-new/gamesemus/yabause/yabauseet/yabause-0.9.12/src/ygl.h:240: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘glDeleteFramebuffers’
/media/DATASUPER/MASSENKOH-new/gamesemus/yabause/yabauseet/yabause-0.9.12/src/ygl.h:241: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘glGenFramebuffers’
/media/DATASUPER/MASSENKOH-new/gamesemus/yabause/yabauseet/yabause-0.9.12/src/ygl.h:242: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘glCheckFramebufferStatus’
/media/DATASUPER/MASSENKOH-new/gamesemus/yabause/yabauseet/yabause-0.9.12/src/ygl.h:243: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘glFramebufferTexture1D’
/media/DATASUPER/MASSENKOH-new/gamesemus/yabause/yabauseet/yabause-0.9.12/src/ygl.h:244: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘glFramebufferTexture2D’
/media/DATASUPER/MASSENKOH-new/gamesemus/yabause/yabauseet/yabause-0.9.12/src/ygl.h:245: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘glFramebufferTexture3D’
/media/DATASUPER/MASSENKOH-new/gamesemus/yabause/yabauseet/yabause-0.9.12/src/ygl.h:246: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘glFramebufferRenderbuffer’
/media/DATASUPER/MASSENKOH-new/gamesemus/yabause/yabauseet/yabause-0.9.12/src/ygl.h:247: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘glGetFramebufferAttachmentParameteriv’
/media/DATASUPER/MASSENKOH-new/gamesemus/yabause/yabauseet/yabause-0.9.12/src/ygl.h:248: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘glGenerateMipmap’
/media/DATASUPER/MASSENKOH-new/gamesemus/yabause/yabauseet/yabause-0.9.12/src/ygl.h:249: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘glBlitFramebuffer’
/media/DATASUPER/MASSENKOH-new/gamesemus/yabause/yabauseet/yabause-0.9.12/src/ygl.h:250: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘glRenderbufferStorageMultisample’
/media/DATASUPER/MASSENKOH-new/gamesemus/yabause/yabauseet/yabause-0.9.12/src/ygl.h:251: error: expected ‘=’, ‘,’, ‘;’, ‘asm’ or ‘__attribute__’ before ‘glFramebufferTextureLayer’
make[4]: *** [src/CMakeFiles/yabause.dir/memory.c.o] Error 1
```

**Comment by rdanbrook** [comment]
Why are you using such old libraries? Of course software being written right now is going to have problems with libraries that are 5 years old.

**Comment by mckaygerhard** [comment]
due i building this on a devices that are not 100% pc or androit, i noted that there's no images of powerpc builds, and in wiki there's very vew (nothing) info to made a binary for powerpc mac users

i like this emulator due are "cross-platform"

**Comment by mckaygerhard** [comment]
can see the YAB_RGB that set pixel format, but are usefully right now?, to compile a full software rendering yabause? please answer!

i can see on the code the chose:
```
set(YAB_RGB "" CACHE STRING "Bit configuration of pixels in the display buffer.")
if (YAB_RGB STREQUAL "555")
    add_definitions(-DUSE_16BPP=1 -DUSE_RGB_555=1)
elseif (YAB_RGB STREQUAL "565")
    add_definitions(-DUSE_16BPP=1 -DUSE_RGB_565=1)
endif ()
```

**Comment by Guillaumito** [comment]
It's only useful for ports that want 16bpp output, it was added for libretro and the Qt port was modified only so I can test it.

**Comment by mckaygerhard** [comment]
16 bpp its usefully for me, i can made a xrandr little bash script that changes on fly the xorg depth for that (umm but i think should work without)

if i build a 16bpp flavor can be work the software render?

please there's any chance to made support to older opengl calls, the 0.9.14+ has many bugfixed that 0.9.11.1 dont have! i can only compiled the 0.9.11, the 0.9.13 (this version its the desired for me) give me the errors that i paste prevously...

and.. do u see the wiki?

**Comment by Rankgel** [comment]
Please i'm also interesting in this, can provide updates to support opengl 1.2 please!

The problem its that most people in many countries only has low end machines, some famous linux gamin distribution compiles a older version of xorg due better performance in variety of low end hardware, also noted that gtk interface are less memory hugred rather than qt5. Moder up-to-date xorg and mesa requires a lot of hadrware capabilities.

**Comment by Guillaumito** [comment]
Sorry, but no, we won't support legacy OpenGL. If your hardware doesn't supports modern OpenGL, use the "full software" mode.

**Comment by mckaygerhard** [comment]
https://en.wikipedia.org/wiki/Smartbook this notebook are x86 but dont run
very faster with your improvements since 0.9.13

https://en.wikipedia.org/wiki/Subnotebook this kind of machines some are
ARM and others X86, yabause now are runs slowly with lasted software

And finally software pure rasterizer dont work!

Lenz McKAY Gerardo (PICCORO)
http://qgqlochekone.blogspot.com

2015-09-03 16:26 GMT-04:30 Guillaume Duhamel <notifications@github.com>:

**Comment by Guillaumito** [comment]
Ok, great, use 0.9.13 then.

**Comment by mckaygerhard** [comment]
No wu said that support build on androit, for these devices: https://en.wikipedia.org/wiki/Netbook build with opengl es 3.X are not supported due hardware!

the target are cheap for users, when able to build recents versions of saturn 

i ironically have a vaste huge collection of games of sarurn and dreamcast some are original, but olders versions of yabause still not provide the fixeds or features of lasted
ironically due i only have and Craig mininetbook with androit and a Smartbook with linux, the 3 saturn now are waste due the lents are gone.

**Comment by Guillaumito** [comment]
I'm sorry Yabause doesn't match your needs, but there's nothing I can do about it. This issue is closed now and as I already said, if you can't use modern OpenGL, try the full software mode. If that still doesn't works for you, buy a Saturn.

**Comment by mckaygerhard** [comment]
i'll now try full software mode, get a black screen on last git on older devices, so i concluyed that minimal mesa version i need are gallium and go (7.99 or 8.0), debian squeeze are not supported sice yabause 0.9.13 due problems in video module

no i begin to use yabause 0.9.14 on a moder machine in my job, and 0.9.11 on my home "older but efficient" devices, some games work in one and does not work in other and viceversa.., i'll report only in github issues those that dont work in 0.9.14 or git but hav been work in older versions..

my collection are vast and huge, a 80% are original buy disc, 16% iso ripped and rest are downloaded (japanesse due they are not sold in latin america) if u doub of my, i can post youtube video for u if necesary

**Comment by mckaygerhard** [comment]
build a software only now finished, video works, external bios dumped (again) works but games not working, freezes at same point described in issues: #76 and #62

the games newer reported not tested yet, need to search at my home if u want, but impliest talk to my brother and he its not happy today!

the builds of software render video implies use in debian derivates the package `libgl1-mesa-swx11-dev` that changes all xorg setup to rasterizer by software and removes DRI support

so for those that builds , must need to test in a DRI capable setup by restoring all previus packages (with mesagl related) or test in other machine like me does!
