### ISSUE TITLE
bomberman wars was now not playable with lasted

### ISSUE THREAD

**Issue by mckaygerhard** [Yabause/yabause#76]
due i not have recent hardware and the only game that i have in file are bomberman wars, in my jod i tested this CUE file.

until 0.9.12 game are playable 100% (in my low cost machines netbook with linux squeeze debian), but since 0.9.13 game freezes at hudson screen logo! i used a machine on my job to test.

the qt interface if are running at this moment show a error:
undefined symbol: _ZN9QListData11detach_growEPii

the gtk interface does not show any error.. i cannot debug in the os due are a machine of the job.

later a guy test a downlaoded binary on windows and works once time and then does not work any more.

**Comment by cyberwarriorx** [comment]
Tested on using latest code from github and works fine.

**Comment by mckaygerhard** [comment]
i currently notified that my opengl must be lasted mesa gallium but as @Guillaumito recommended i build now the software only and the rom are not working, must i provide a video for ? the build its not working in some setups, by example eepc arm builds and xandros x86 builds

**Comment by cyberwarriorx** [comment]
The issue was titled "Bomberman Wars not playable in lasted(latest?)". I tested it on the latest version and it does work fine. I tested both using opengl and software rendering and of course using Qt4.
