### ISSUE TITLE
Screenshot error with Linux

### ISSUE THREAD

**Issue by Marc34** [Yabause/yabause#77]
Hi

On Linux (Manjaro, Linux Mint), whatever I do (opengl, software renderer, pause while screenshot, trying jpg, png etc), it is impossible to take screenshot with Yabause 0.9.13 or the last compiled version.

The message is : An error occur while writing the screenshot.

**Comment by Guillaumito** [comment]
Which port are you using? Gtk or Qt?

**Comment by Marc34** [comment]
Qt.

**Comment by mckaygerhard** [comment]
i'm confirm this on previous version 0.9.13, as i post in the other issue, remenber?

**Comment by Guillaumito** [comment]
I think it's a problem with filenames. Can you try saving a screenshot again and include the extension in the filename. For instance, if you want to save a png screenshot, try to name your file something like "yabause-screenshot.png"?

**Comment by mckaygerhard** [comment]
i'll made more test on monday with the machine in my job due my olders versions seems yet works, current git for me dont compile and dont work at my home machines, remenber

**Comment by Marc34** [comment]
You're right, it works with the extension ! Thanks.

**Comment by Guillaumito** [comment]
Somehow fixed in 2d3f3546c9aca7b2727dfd62c746d72f5fb6d176
