### ISSUE TITLE
qt multimedia setup fixeds for debian derivates that lacks qt-multimedia on qt4

### ISSUE THREAD

**Issue by mckaygerhard** [Yabause/yabause#84]
this its a rare case, only tested in and laptop with qt4 only 4.7.4

in the line https://github.com/Yabause/yabause/blob/9ea2ceb606e0cf30810b95d925fa25dc57df63fe/yabause/src/qt/CMakeLists.txt#L29 the qt multimedia are set and then for some cmake setups this meas force to use it, that relies on and error event if later in https://github.com/Yabause/yabause/blob/9ea2ceb606e0cf30810b95d925fa25dc57df63fe/yabause/src/qt/CMakeLists.txt#L44 are try to not use it..

thats why for some setupd in line https://github.com/Yabause/yabause/blob/9ea2ceb606e0cf30810b95d925fa25dc57df63fe/yabause/src/qt/CMakeLists.txt#L29 trows an error before the line 9ea2ceb606e0cf30810b95d925fa25dc57df63fe/yabause/src/qt/CMakeLists.txt#L44

my suggestions its remove the line ` set ( QT_USE_QTMULTIMEDIA TRUE )`  due in winbuntu and debian based since qt 4.7 are not property setup (its removed and i dont know why), but for qt5 seems its shiped (not tested yet)

then push in the contitional as:

```
	if (QT_QTMULTIMEDIA_FOUND)
		set ( QT_USE_QTMULTIMEDIA TRUE ) # line altered and added here
		add_definitions(-DHAVE_QT_MULTIMEDIA=1)
	endif ()
```

solves that error when compiling in qt4 setups for debian derivates:

Qt QTMULTIMEDIA library not found.
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.

**Comment by cyberwarriorx** [comment]
For debian they separated qtmultimedia into a separate package

**Comment by mckaygerhard** [comment]
only for qt5, for qt4 only qt 4.6.3 has qt multimedia, in any case, the conditionall must be done if package are not detected

@cyberwarriorx please can u help me where are the package in debian packages search for qt 4.X i only noted for qt 4.6.3 ont for 4.7.4?

**Comment by cyberwarriorx** [comment]
Why are you using versions of Qt from like five/six years ago? Even 4.8.x series started in 2011. That's **four** years ago. We're currently transitioning to Qt5 since Qt Company themselves are dropping official support by the end of this year.

**Comment by mckaygerhard** [comment]
becose qt4 are supporte, are faster rather than and compiles better in some arm devices such eepc adn some androit with maebo older versions

the qt4 interface are working good, and this little fix are only a line change! qt4 gemme better loads rather qt5 that consumes a lod more of memory , in lxde-qt project reconices that qt5 takes more memory rather qt4: https://groups.google.com/d/msg/razor-qt/O9V4jrMxOrU/0q86-5FCEf0J here are a seed when a qt4 app port to qt5 obviusly memory and cpu are higgher, so i used qt4 due are more cheap to devices respect performance

what's the problem its a two lines change!

**Comment by cyberwarriorx** [comment]
It still doesn't change the fact you're using seriously old versions of Qt4

**Comment by mckaygerhard** [comment]
well event used qt4 lasted its faild, debian qt4 lacks of qt-multimedia, only are for qt5, 
note that i used older qt4 version due are more preformance rater than qt5, asus eepc, xandrosos, arm eepc, maebo (some) olders androit, and many low-end machines still need fewer depends, due recent linux does not fit in see "samrtbook" and "minibook" laptos in wikipedia
why so noise for a simple patch, i provided! i not ask for a patch, i provided! i collaborate!

**Comment by cyberwarriorx** [comment]
Then use Qt 4.8.7 then. Or heck anything from the last couple of years would be an improvement.

If this is a patch you posted it in the wrong section then. You need to do a pull request.

**Comment by mckaygerhard** [comment]
qt 4.8.7 does not fill qt multimedia in debian!

**Comment by mckaygerhard** [comment]
a rejection notable way, diverting attention just because I make this work for other older platforms used in countries that are very poor, I think is not the way to treat users as well! what a disappointment!

**Comment by cyberwarriorx** [comment]
Quit trying to deflect the topic in a way that makes no sense. You claim there's a bug while compiling with an old version of Qt, I suggest not using an old version. You say there's a patch in here, I say this is not the avenue for it(Github has something called pull requests for that). Just use the proper channels if you want a patch included.
